apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-api
  template:
    metadata:
      labels:
        app: nodejs-api
    spec:
      containers:
      - name: nodejs-api
        image: fredwinrosales/nodejs-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            ephemeral-storage: "100Mi"
          limits:
            ephemeral-storage: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-api-service
spec:
  selector:
    app: nodejs-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
